apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: mordred
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-14.2-0
  postgresVersion: 14
  instances:
    - name: instance1
      replicas: 2
      dataVolumeClaimSpec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  # monitoring:
  #   pgmonitor:
  #     exporter:
  #       image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:latest
  monitoring:
    pgmonitor:
      exporter:
        image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.0.5-0
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.36-1
      configuration:
        - secret:
            name: pgo-s3-creds
      global:
        repo1-path: /debug/dev/mordred01
        repo1-retention-full: "14"
        repo1-retention-full-type: count
      manual:
        repoName: repo1
        options:
          - --type=full
      repos:
        - name: repo1
          schedules:
            full: "0 1 * * *"
            incremental: "0 */4 * * *"
          s3:
            bucket: "devcluster"
            endpoint: "s3.eu-west-1.wasabisys.com"
            region: "eu-west-1"
      # restore:
      #   enabled: true
      #   repoName: repo1
      #   options:
      #     - --type=time
      #     - --target="2022-03-08 11:30:00"
